# Generated by Django 5.2 on 2025-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_category_alter_customuser_phone_number_cart_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="category_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product_images/"),
        ),
    ]
